apiVersion: v1
kind: Service
metadata:
  name: ind-web-frontend-lb
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: ind-web-frontend
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata: 
  labels:
    run: ind-web-frontend
  name: ind-web-frontend
spec:
  selector:
    matchLabels:
      run: ind-web-frontend
  template:
    metadata:
      labels:
        run: ind-web-frontend
    spec:
      containers:
      - name: web-frontend
        image: indcr.azurecr.io/web_frontend:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    run: ind-controller
  name: ind-controller
spec:
  selector:
    matchLabels:
      run: ind-controller
  template:
    metadata:
      labels:
        run: ind-controller
    spec:
      containers:
        - name: controller
          image: indcr.azurecr.io/controller:latest
          ports:
            - containerPort: 5002
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: ind-controller-ci
spec:
  type: ClusterIP
  ports:
    - name: "5002"
      port: 5002
      targetPort: 5002
  selector:
    run: ind-controller
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    run: ind-api-server
  name: ind-api-server
spec:
  selector:
    matchLabels:
      run: ind-api-server
  template:
    metadata:
      labels:
        run: ind-api-server
    spec:
      containers:
      - name: api-server
        image: indcr.azurecr.io/api_server:latest
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: ind-api-server-ci
spec:
  type: ClusterIP
  ports:
  - name: "5001"
    port: 5001
    targetPort: 5001
  selector:
    run: ind-api-server
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    run: ind-worker
  name: ind-worker
spec:
  selector:
    matchLabels:
      run: ind-worker
  template:
    metadata:
      labels:
        run: ind-worker
    spec:
      containers:
      - name: worker
        image: indcr.azurecr.io/worker:latest
        ports:
        - containerPort: 5003
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ind-web-frontend-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ind-web-frontend
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ind-controller-hpa
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ind-controller
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ind-api-server-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ind-api-server
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ind-worker-hpa
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ind-worker
  targetCPUUtilizationPercentage: 50
