apiVersion: v1
kind: Service
metadata:
  name: ind-lb
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: ind
  type: LoadBalancer
---
kind: Deployment
metadata: 
  labels:
    run: ind
  name: ind
spec:
  selector:
    matchLabels:
      run: ind
  template:
    metadata:
      labels:
        run: ind
    spec:
      containers:
      - name: web-frontend
        image: indcr.azurecr.io/web_frontend:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m

      - name: api-server
        image: indcr.azurecr.io/api_server:latest
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
      - name: worker
        image: indcr.azurecr.io/worker:latest
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ind-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ind
  targetCPUUtilizationPercentage: 50

